spring:
  application:
    name: reactive
  datasource:
    url: jdbc:mysql://localhost:3306/project
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
server:
  port: 8092





